<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.agnetix</groupId>
        <artifactId>harnax</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>harnax-agent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>harnax-agent</name>
    <url>http://maven.apache.org</url>

    <modules>
        <module>harnax-agent-utils</module>
        <module>harnax-agent-core</module>
        <module>harnax-harness-core</module>
        <module>harnax-agent-service</module>
    </modules>

</project>
