package com.agnetix.harnax.admin.dto.mp

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.constraints.NotBlank

@Schema(description = "Create mobile session request")
data class MpCreateSessionRequest(
    @Schema(description = "Session name", example = "New Chat")
    @field:NotBlank(message = "Session name is required")
    val sessionName: String = "",

    @Schema(description = "Corresponding router session ID (optional, generated by client)")
    val routerSessionId: String? = null,
)
