package com.agnetix.harnax.admin.controller

import com.agnetix.harnax.admin.config.AdminMinioProperties
import com.agnetix.harnax.admin.util.JwtUtil
import com.agnetix.harnax.admin.util.UserContextUtil
import com.agnetix.harnax.mapper.ChannelMapper
import io.minio.GetObjectArgs
import io.minio.MinioClient
import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.tags.Tag
import org.slf4j.LoggerFactory
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty
import org.springframework.http.HttpHeaders
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController

/**
 * Output file download proxy controller.
 *
 * Proxies file downloads from MinIO with permission checking.
 * MinIO is not exposed externally — all downloads go through this endpoint.
 *
 * URL pattern: /api/output-files/{sessionType}/{sessionId}/{fileId}
 * - sessionType: "web" | "task" | "channel"
 *
 * Permission model:
 * - Channel files: verifies the channel belongs to the current logged-in user
 * - Web/Task session files: any authenticated user can download
 */
@RestController
@RequestMapping("/api/output-files")
@Tag(name = "Output File Download", description = "Proxy download for agent output files")
@ConditionalOnProperty(prefix = "minio", name = ["enabled"], havingValue = "true")
class OutputFileController(
    private val minioClient: MinioClient,
    private val minioProperties: AdminMinioProperties,
    private val channelMapper: ChannelMapper,
    private val jwtUtil: JwtUtil,
) {
    private val log = LoggerFactory.getLogger(OutputFileController::class.java)

    companion object {
        // UUID pattern for fileId validation (prevents path traversal)
        private val UUID_PATTERN = Regex("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")

        // sessionId: alphanumeric, dash, underscore only
        private val SESSION_ID_PATTERN = Regex("^[a-zA-Z0-9_-]{1,128}$")

        // Allowed session types
        private val VALID_SESSION_TYPES = setOf("web", "task", "channel")
    }

    /**
     * Download output file with permission check.
     * URL: /api/output-files/{sessionType}/{sessionId}/{fileId}?name=report.pptx
     *
     * Permission:
     * - channel: verifies the channel belongs to the current logged-in user
     * - web/task: any authenticated user can download
     */
    @GetMapping("/{sessionType}/{sessionId}/{fileId}")
    @Operation(summary = "Download output file", description = "Downloads a file generated by agent. Channel files require ownership; web/task files require authentication.")
    fun downloadFile(
        @PathVariable sessionType: String,
        @PathVariable sessionId: String,
        @PathVariable fileId: String,
        @RequestParam(defaultValue = "download") name: String,
    ): ResponseEntity<ByteArray> {
        // 0. Input validation
        if (sessionType !in VALID_SESSION_TYPES) {
            return ResponseEntity.badRequest().build()
        }
        if (!UUID_PATTERN.matches(fileId) || !SESSION_ID_PATTERN.matches(sessionId)) {
            return ResponseEntity.badRequest().build()
        }

        // 1. Authentication
        val currentUsername = try {
            UserContextUtil.getCurrentUsername(jwtUtil)
        } catch (e: Exception) {
            return ResponseEntity.status(401).build()
        }

        // 2. Authorization: channel files require ownership check
        if (sessionType == "channel") {
            // sessionId format: chn-{channelId}-{userId}
            val channelId = sessionId.removePrefix("chn-").substringBefore("-").toLongOrNull()
                ?: return ResponseEntity.badRequest().build()
            val channel = channelMapper.selectById(channelId)
                ?: return ResponseEntity.notFound().build()
            if (channel.creator != currentUsername) {
                log.warn("[outputFile] Permission denied: user '{}' attempted to download from channel {} (owner: '{}')", currentUsername, channelId, channel.creator)
                return ResponseEntity.status(403).build()
            }
        }

        // 3. Read file from MinIO
        val objectKey = "$sessionType/$sessionId/$fileId"
        val bytes = readFromMinio(objectKey)
            ?: return ResponseEntity.notFound().build()

        log.info("[outputFile] User '{}' downloaded '{}' ({} bytes) from {}/{}", currentUsername, name, bytes.size, sessionType, sessionId)

        // 4. Return file stream
        val safeName = sanitizeFileName(name)
        return ResponseEntity.ok()
            .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"$safeName\"")
            .contentType(MediaType.APPLICATION_OCTET_STREAM)
            .contentLength(bytes.size.toLong())
            .body(bytes)
    }

    /**
     * Sanitize file name for Content-Disposition header.
     * Removes quotes, CR/LF, and non-printable characters to prevent header injection.
     */
    private fun sanitizeFileName(name: String): String {
        val cleaned = name
            .replace("\"", "")
            .replace("\r", "")
            .replace("\n", "")
            .replace(";", "")
            .trim()
        return cleaned.ifEmpty { "download" }
    }

    private fun readFromMinio(objectKey: String): ByteArray? = try {
        minioClient.getObject(
            GetObjectArgs.builder()
                .bucket(minioProperties.outputBucket)
                .`object`(objectKey)
                .build(),
        ).use { it.readBytes() }
    } catch (e: Exception) {
        log.warn("[outputFile] Failed to read object '{}': {}", objectKey, e.message)
        null
    }
}
